server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical_care_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: cxy-20060621
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity